# System Representation Gallery

This Jupyter notebook creates different types of systems and generates a variety of representations (`__repr__`, `__str__`) for those systems that can be used to compare different versions of python-control.  It is mainly intended for uses by developers to make sure there are no unexpected changes in representation formats, but also has some interesting examples of different choices in system representation.

In [1]:
import numpy as np

import control as ct
import control.flatsys as fs

ct.__version__

'0.10.1.dev324+g2fd3802a.d20241218'

## Text representations

The code below shows what the output in various formats will look like in a terminal window.

In [2]:
# Grab system definitions (and generate various representations as text)
from repr_gallery import *

                                Default repr

StateSpace: sys_ss, dt=0:
-------------------------
StateSpace(
array([[ 0.,  1.],
       [-4., -5.]]),
array([[0.],
       [1.]]),
array([[-1.,  1.]]),
array([[0.]]),
name='sys_ss', states=2, outputs=1, inputs=1)
----

StateSpace: sys_dss, dt=0.1:
----------------------------
StateSpace(
array([[ 0.98300988,  0.07817246],
       [-0.31268983,  0.59214759]]),
array([[0.00424753],
       [0.07817246]]),
array([[-1.,  1.]]),
array([[0.]]),
dt=0.1,
name='sys_dss', states=2, outputs=1, inputs=1)
----

StateSpace: stateless, dt=None:
-------------------------------
StateSpace(
array([], shape=(0, 0), dtype=float64),
array([], shape=(0, 2), dtype=float64),
array([], shape=(2, 0), dtype=float64),
array([[1., 0.],
       [0., 1.]]),
dt=None,
name='stateless', states=0, outputs=2, inputs=['u0', 'u1'])
----

TransferFunction: sys_ss$converted, dt=0:
-----------------------------------------
TransferFunction(
array([ 1., -1.]),
array([1., 5., 4.]),
na

## Jupyter notebook (HTML/LaTeX) representations

The following representations are generated using the `_html_repr_` method in selected types of systems.  Only those systems that have unique displays are shown.

### Continuous time state space systems

In [3]:
sys_ss

StateSpace(
array([[ 0.,  1.],
       [-4., -5.]]),
array([[0.],
       [1.]]),
array([[-1.,  1.]]),
array([[0.]]),
name='sys_ss', states=2, outputs=1, inputs=1)

In [4]:
with ct.config.defaults({'statesp.latex_repr_type': 'separate'}):
    display(sys_ss)

StateSpace(
array([[ 0.,  1.],
       [-4., -5.]]),
array([[0.],
       [1.]]),
array([[-1.,  1.]]),
array([[0.]]),
name='sys_ss', states=2, outputs=1, inputs=1)

In [5]:
with ct.config.defaults({
    'statesp.latex_repr_type': 'separate',
    'statesp.latex_num_format': '8.4f'}):
    display(sys_ss)

StateSpace(
array([[ 0.,  1.],
       [-4., -5.]]),
array([[0.],
       [1.]]),
array([[-1.,  1.]]),
array([[0.]]),
name='sys_ss', states=2, outputs=1, inputs=1)

### Stateless state space system

In [6]:
sys_ss0

StateSpace(
array([], shape=(0, 0), dtype=float64),
array([], shape=(0, 2), dtype=float64),
array([], shape=(2, 0), dtype=float64),
array([[1., 0.],
       [0., 1.]]),
dt=None,
name='stateless', states=0, outputs=2, inputs=['u0', 'u1'])

In [7]:
with ct.config.defaults({'statesp.latex_repr_type': 'separate'}):
    display(sys_ss0)

StateSpace(
array([], shape=(0, 0), dtype=float64),
array([], shape=(0, 2), dtype=float64),
array([], shape=(2, 0), dtype=float64),
array([[1., 0.],
       [0., 1.]]),
dt=None,
name='stateless', states=0, outputs=2, inputs=['u0', 'u1'])

### Discrete time state space system

In [8]:
sys_dss

StateSpace(
array([[ 0.98300988,  0.07817246],
       [-0.31268983,  0.59214759]]),
array([[0.00424753],
       [0.07817246]]),
array([[-1.,  1.]]),
array([[0.]]),
dt=0.1,
name='sys_dss', states=2, outputs=1, inputs=1)

### "Stateless" state space system

In [9]:
sys_ss0

StateSpace(
array([], shape=(0, 0), dtype=float64),
array([], shape=(0, 2), dtype=float64),
array([], shape=(2, 0), dtype=float64),
array([[1., 0.],
       [0., 1.]]),
dt=None,
name='stateless', states=0, outputs=2, inputs=['u0', 'u1'])

### Continuous time transfer function

In [10]:
sys_tf

TransferFunction(
array([ 1., -1.]),
array([1., 5., 4.]),
name='sys_ss$converted', outputs=1, inputs=1)

In [11]:
with ct.config.defaults({'xferfcn.display_format': 'zpk'}):
    display(sys_tf)

TransferFunction(
array([ 1., -1.]),
array([1., 5., 4.]),
name='sys_ss$converted', outputs=1, inputs=1)

### MIMO transfer function

In [12]:
sys_mtf  # SciPy generates a warning due to 0 numerator in 1, 2 entry

/Users/murray/miniconda3/envs/python3.13-slycot/lib/python3.13/site-packages/scipy/signal/_filter_design.py:1112: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  b, a = normalize(b, a)
/Users/murray/miniconda3/envs/python3.13-slycot/lib/python3.13/site-packages/scipy/signal/_filter_design.py:1116: RuntimeWarning: invalid value encountered in divide
  b /= b[0]


TransferFunction(
[[array([ 1., -1.]), array([0.])],
 [array([1, 0]), array([1, 0])]],
[[array([1., 5., 4.]), array([1.])],
 [array([1]), array([1, 2, 1])]],
name='sys_mtf_zpk', outputs=2, inputs=2)

### Discrete time transfer function

In [13]:
sys_dtf

TransferFunction(
array([ 0.07392493, -0.08176823]),
array([ 1.        , -1.57515746,  0.60653066]),
dt=0.1,
name='sys_dss_poly', outputs=1, inputs=1)

### Linear interconnected system

In [14]:
sys_lic

<LinearICSystem sys_ic: ['r[0]', 'r[1]'] -> ['y[0]', 'y[1]']>

### Non-HTML capable system representations

In [15]:
for sys in [sys_frd, sys_nl, sys_ic, sys_fs]:
    display(sys)

FrequencyResponseData(
array([[[-0.24365959+0.05559644j, -0.19198193+0.1589174j ,
          0.05882353+0.23529412j,  0.1958042 -0.01105691j,
          0.0508706 -0.07767156j]]]),
array([ 0.1       ,  0.31622777,  1.        ,  3.16227766, 10.        ]),
name='sys_ss$converted$sampled', outputs=1, inputs=1)

<NonlinearIOSystem sys_nl: ['u[0]'] -> ['y[0]']>

<InterconnectedSystem sys_ic: ['r[0]', 'r[1]'] -> ['y[0]', 'y[1]']>

<FlatSystem sys_fs: ['u[0]'] -> ['y[0]']>